### ISSUE TITLE
BUG: Try-catches around callback execution

### ISSUE THREAD

**Issue by brianreavis** [thingdom/node-neo4j#139]
It is a really bad practice to throw exceptions inside of async code and right now node-neo4j is littered with this. Even worse, there are try/catches around where user callbacks are executed. Can both of these things be fixed? (**Edit:** Not the problem because of code transformation through [streamline](https://github.com/Sage/streamlinejs)) I would offer to refactor, but it's in CoffeeScript (another discussion).

Why is it bad? It makes debugging of exceptions completely unrelated to node-neo4j nearly impossible (just spent an hour doing it). For example, here is a stack trace:

```
TypeError: undefined is not a function
    at /var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/streamline/lib/callbacks/runtime.js:169:5
    at Object.__g.trampoline.flush (/var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/streamline/lib/callbacks/runtime.js:23:29)
    at Request.___ [as _callback] (/var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/streamline/lib/callbacks/runtime.js:120:61)
    at Request.self.callback (/var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/local/naturalatlas.com/node_modules/neo4j/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**The cause:** an `undefined` function elsewhere in the application.

Here's a simplified scenario:

``` js
var done = function() {
    var x = a; // "a" not defined (throws)
};

neo4j.query('somequery', {}, function(err, results) { done(); });
```

In this example, the TypeError gets caught by neo4j and fails erratically with a stack trace like above.
